# Generated by Django 5.0.6 on 2024-08-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceevent',
            name='distance',
            field=models.CharField(choices=[('10K', '10K'), ('HM', 'Half Marathon'), ('M', 'Marathon'), ('53K', '53K Ultra')], max_length=3),
        ),
    ]
