# Generated by Django 5.0.6 on 2024-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_gpxfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxfile',
            name='file',
            field=models.FileField(upload_to='gpx_files/'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
