# Generated by Django 5.0.6 on 2024-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_gpxfile_file_alter_gpxfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxfile',
            name='file',
            field=models.BinaryField(),
        ),
    ]
