# Generated by Django 5.0.6 on 2024-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_gpxfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
